### ISSUE TITLE
Player fails to load in Android

### ISSUE THREAD

**Issue by arthurgeron-work** [aws/amazon-ivs-react-native-player#100]
**Describe the bug**
Video does not play on android, the player stays in a loading loop, each load it crashes and then starts again. It only received one quality instruction, but seems to try to change from a valid quality into nothing and then crash.

**To reproduce**
Using version 1.2.0, try loading the following URL in a react-native application: `https://mobile.tradersclub.com.br/tcmediaapi/v1/file/hls/685d3dae-2f68-4f2f-be44-82a20f687716.m3u8`
I'm not using expo

**Expected behavior**
Should play the stream correctly

**Screenshots**

**Device (please complete the following information):**
 - Simulator or Real Device: Real Device
 - Device: Samsung a11
 - OS: One UI Core 3.1, Android 11
 
**Debug logs**

Qualities received from stream:
` [{"bitrate": 5241789, "codecs": "avc1.640032,mp4a.40.2", "framerate": 0, "height": 2274, "name": "2274p", "width": 1280}]`
On App Launch the following is logged:
`Could not find generated setter for class com.amazonaws.ivs.reactnative.player.AmazonIvsViewManager`
`Could not find generated setter for class com.perrystreet.AwsIvsPlayerViewManager`
![image](https://user-images.githubusercontent.com/71399856/195651613-d5a4400d-84dc-4696-9507-670a263a2744.png)

When video tries to play it logs:

SS P1:   
![Captura de Tela 2022-10-13 às 13 27 03](https://user-images.githubusercontent.com/71399856/195652866-68bc2b5f-d073-4992-baab-4118aaa6eb25.png).  
SS P2:   
![Captura de Tela 2022-10-13 às 13 25 22](https://user-images.githubusercontent.com/71399856/195652515-06d17b36-4234-4264-b1dd-1851f6a5c08a.png)

**Comment by maxstoller** [comment]
Please see my comment here: https://github.com/aws/amazon-ivs-react-native-player/issues/99#issuecomment-1277907851. It looks like the same root cause. Does this occur when you use IVS content? e.g. https://github.com/aws-samples/amazon-ivs-player-web-sample#test-streams

**Comment by arthurgeron-work** [comment]
Indeed it's the exact same issue, I don't know what happened but it seems like the github API duplicated the issue. Sorry for that
