### ISSUE TITLE
Accessing textMetadataCue at any given time, and not only when it changes

### ISSUE THREAD

**Issue by Enzo-Parodi** [aws/amazon-ivs-react-native-player#107]
I am using IVSPlayer to consume a livestream which contains metadata, and I can access it through the `onTextMetadataCue` prop, but not before. So if I start watching a livestream that is ongoing, I cannot see the text metadata until it changes. 

Is there a way in which I could access the current text metadata before it changes for the first time since I'm watching?

**Comment by maxstoller** [comment]
Hi @Enzo-Parodi, 

Timed metadata is embedded in the video segments. The `onTextMetadataCue` callback will be invoked when the player plays a video segment with timed metadata in it. Are you trying to programmatically access the most recently seen metadata? If so, you will have to handle that in the application. The SDK does not hold on to this value. What is your use case?

**Comment by Enzo-Parodi** [comment]
Hi @maxstoller, thanks for the reply.
What I am trying to do is to access the textMetadata of a livestream at the moment when I, as a viewer, start consuming a livestream that was already active by the time I started watching it.
As far as I know, I can only access the text metadata through the `onTextMetadataCue`, which is triggered when the text metadata changes, but not before (during the time between starting to watch a livestream and the first text metadata update that I as a viewer see). This metadata is attached on our backend and gets updated whenever the user who created the livestream changes it.

Our current solution is saving the same data we use for the text metadata in our db and request separately to our api when starting to watch a livestream. After that, we update it using the `onTextMetadataCue`.

**Comment by maxstoller** [comment]
Yes, the player does not expose timed metadata from earlier in the live stream. Your current solution seems like a good approach.

**Comment by dawhitla** [comment]
Closing this issue as a solution was given, and there has been no further questions 👍
