### ISSUE TITLE
Add an option to set video resize behaviour

### ISSUE THREAD

**Issue by chitosai** [aws/amazon-ivs-react-native-player#12]
Hi there, 

I notice that when the ratio of video is different from the player, the player applies a contain mode that shows the whole video with black bars on sides.
Can we add an option to control this resize behaviour, for example
```
resize: contain | cover | stretch
```

Thanks

**Comment by floelm** [comment]
I would also like to see this feature in the future. Right now I am doing some hacky workaround which basically checks the aspect ratio of the stream quality and compares it with the aspect ratio of the phone and applies transform with scale on the style property to scale it up or down

**Comment by alexmdodge** [comment]
@chitosai `resizeMode` has been included and deployed as part of the `1.1.0` release:
https://github.com/aws/amazon-ivs-react-native-player/blob/main/docs/ivs-player-reference.md#resizemode-optional

**Comment by chitosai** [comment]
> @chitosai `resizeMode` has been included and deployed as part of the `1.1.0` release: https://github.com/aws/amazon-ivs-react-native-player/blob/main/docs/ivs-player-reference.md#resizemode-optional

@alexmdodge Great job. Thanks so much!
