### ISSUE TITLE
SeekTo is convert to int position passed in android but not in ios

### ISSUE THREAD

**Issue by kailashgoswami** [aws/amazon-ivs-react-native-player#124]
**In Android** 
If we call seekTo with fraction number like seekTo(10.25)   then it convert to int the position we passed. It will move video to 10 sec not to 10.25.
**In IOS** 
It will not convert to int it is using fraction value that we passed. It will move video to 10.25 sec.

**Comment by maxstoller** [comment]
Hi @kailashgoswami, thanks for the feedback. We will look into this and see if we can make it more consistent across platforms.

**Comment by kailashgoswami** [comment]
Hi @maxstoller  Any update on this bug. 


I can see similar changes in this PR https://github.com/aws/amazon-ivs-react-native-player/pull/112

Are these changes will fix this ? If not
