### ISSUE TITLE
Support for strict origin enforcement

### ISSUE THREAD

**Issue by joelennon** [aws/amazon-ivs-react-native-player#129]
Amazon IVS supports strict origin enforcement when creating playback tokens, as per the documentation here:

https://docs.aws.amazon.com/ivs/latest/userguide/private-channels-generate-tokens.html

The IVS iOS and Android player SDKs include a method `setOrigin` which allows us to set the origin header as required for this setting, but this method is not available via this library. Would it be possible to support this feature in the React Native library?

**Comment by maxstoller** [comment]
Hi @joelennon,

Yes, we will plan to expose setOrigin the wrapper. Thanks for the feedback.

Max
