### ISSUE TITLE
Asset validation failed -  non-public symbols 

### ISSUE THREAD

**Issue by c-bahar** [aws/amazon-ivs-react-native-player#144]
**Describe the bug**
I started getting error while uploading my app to TestFlight.

Asset validation failed - The app references non-public symbols in Payload/***/Frameworks/AmazonIVSPlayer.framework/AmazonIVSPlayer: _CMTimebaseCreateWithMasterClock

**To reproduce**
I did not change anything, I just started getting error today. I uploaded successfully two weeks ago. I am trying to upload version I uploaded successfully two weeks ago and I am getting same error. I don't know what the change is.

**Screenshots**

<img width="704" alt="Screenshot 2023-07-06 at 11 42 44" src="https://github.com/aws/amazon-ivs-react-native-player/assets/32809976/d3bad08c-6c46-4cab-8f9e-056625bfd60e">

**Device (please complete the following information):**

Uploading to TestFlight

Xcode Version: 14.2

**Comment by Lunziyuan** [comment]
+1
<img width="1324" alt="image" src="https://github.com/aws-samples/amazon-ivs-player-ios-sample/assets/31342448/3d130e97-ac0c-4ec4-813b-ff80b2b6d88f">

**Comment by profugocanis** [comment]
+1

**Comment by Bowlerr** [comment]
+1

**Comment by maxstoller** [comment]
Thanks for the report. We are looking into this and will get back to you here.

**Comment by Jackie404** [comment]
+1

**Comment by mmmcloughlin** [comment]
+1

**Comment by JavierGaMa** [comment]
+1

**Comment by c-bahar** [comment]
As mentioned here, https://developer.apple.com/forums/thread/733318?page=2, bug was resolved by Apple. I tried and did not face any problem. Thus, I am closing the issue.
