### ISSUE TITLE
Way more frame Drops compared to alternatives

### ISSUE THREAD

**Issue by floelm** [aws/amazon-ivs-react-native-player#32]
Hello,

Thank you for providing this package.

I have tried using it for one of my projects but unfortunately compared other video players like `react-native-video` I experience constantly frame drops with this package as a player.
I tried playing around with the settings a bit even though it seems like leaving everything on auto is the best I did not manage to improve this.

So basically with `react-native-video` I am not dropping any frames with the same devices / internet setup but with this package it is more a picture gallery.

Thank you for the work and I am happy to provide more info if needed.

Edit: Lowering the bitrate on streamer side does not change this.
Also AWS IVS sees no issue.

**Comment by maxstoller** [comment]
Hi @floelm, 

Thanks for the feedback! 

Just to confirm, are you using this SDK to play IVS streams (i.e. is your streamUrl an IVS URL)? We have not tested it against third-party content.

Also, can you please try playing an [IVS test stream](https://github.com/aws-samples/amazon-ivs-player-web-sample#test-streams
) and see if you still experience a lot of frame drops? This issue could be related to the content you are playing.

Thanks

**Comment by floelm** [comment]
Hi @maxstoller,

Yes I am using this SDK to view my own IVS stream. No third party content.

I tried your test streams and they are also "dropping frames". I am putting this here into quotation marks because I cannot actually tell if it is dropped frames or just lagging?! I am right now on Android which does not provide the dropped frames data via the Callback. I tried the 1080, 720 and vertical test stream. Basically the video stutters and then skips to the latest part. I assume that is the definition of dropped frames :D

Some other things that could matter:
- Platform Android as mentioned
- latest version of this package (0.2.8)
- react-native 0.64.0

**Comment by maxstoller** [comment]
Thanks. Do you see this same issue when using the example Android app provided in the repo?

If so, can you please post debug logs? You can turn on debug logging using the [logLevel prop](https://github.com/aws/amazon-ivs-react-native/blob/main/docs/ivs-player-reference.md#loglevel-optional).

Can you also share a screen recording so we can see what's happening?

**Comment by floelm** [comment]
Hey,

short update:

I did not have the time yet to check out the example app in the repo but it seems to be an issue that only occurs on Emulator for me. I had the chance now to get it with two real devices and everything worked fine :)

**Comment by maxstoller** [comment]
Great to hear, thanks for the update.

**Comment by alexmdodge** [comment]
@floelm Any additional concerns on your end for this issue? If not I'll close this out 👍

**Comment by floelm** [comment]
No concerns right now, closing it!
