### ISSUE TITLE
other screens or back to screen  are unresponsive after closing player

### ISSUE THREAD

**Issue by RupamShaw** [aws/amazon-ivs-react-native-player#43]
"amazon-ivs-react-native-player": "^1.0.0",
    "react-native": "0.64.3",
   "react-navigation": "^4.4.0",
after closing this player screen whole project is unresponsive
I am using thirdparty streaming then I think only this issue occurs. But for IVS streaming its working.

**Comment by alexmdodge** [comment]
Hi @RupamShaw! Thanks for submitting this report. The IVS React Native player does not support streaming of third party content. Only IVS streams are supported at this time.

I know you mentioned it's working for IVS streams. Could you still provide a log of the failure to see if this is something else we could help with? It may be beneficial to investigate in the future in case this also comes up for IVS content.

**Comment by RupamShaw** [comment]
Thanks as its working with IVS so for me no issues now
