### ISSUE TITLE
streaming video is of 1080p but recieving low bitrate

### ISSUE THREAD

**Issue by RupamShaw** [aws/amazon-ivs-react-native-player#44]
How could I get  1080P with around 8500kbps in player 

```
"amazon-ivs-react-native-player": "^1.0.0",
 "react-native": "0.64.3",
```

streaming is of 1080P with 8500kbps

streaming with amazon-ivs-broadcast-ios-sample

streaming quality

```

AVC profile	Main
AVC level	4.2
Resolution	1080 x 1920
Target bitrate	8,500 kbps
Target framerate	60
Video codec	avc1.4D002A
Audio codec	mp4a.40.2
Target audio bitrate	160 kbps
Audio sample rate	48 kHz
Number of audio channels	 2
```

 I have good internet connection 71.2 Mbps download 27.5 MBps upload 

```
onVideoStatistics={(qvd) => {
        if (qvd?.duration) {
          console.log(`onVideoStatistics ${JSON.stringify(qvd?.bitrate)}`)
          props.onSetBit(`${parseInt(parseInt(qvd?.bitrate) / 1000)} kbps`)
        }
      }}

```
above bitrate sometimes 35kbps to 
Output in player is not more than 2500KBPS

so how to  get such a high quality in player  because our app need crystals clear streaming.

Please let me know is there a way to improve quality tried with these option also but nothing worked

```
     autoMaxQuality={{
         bitrate: 8500000,
         codecs: 'avc1.4D002A,mp4a.40.2',
         framerate: 60,
         height: 1920,
         name: '1920p60',
         width: 1080,
      }}
      
 autoQualityMode={false}
    quality={{
   bitrate: 8500000,
 codecs: 'avc1.4D002A,mp4a.40.2',
 framerate: 60,
  height: 1920,
 name: '1920p60',
     width: 1080,
     }}
```

**Comment by alexmdodge** [comment]
Hi @RupamShaw! Thanks for submitting this report. Can you confirm a couple of details about the issue you've encountered?

* Are you testing on a physical iPhone, or a simulator? If so, which OS version?
* Can you provide any logs or network captures from your session?
* Can you confirm what streams you're testing with? i.e. are these the provided [IVS Test Streams](https://github.com/aws-samples/amazon-ivs-player-web-sample#test-streams) or are these other personal IVS streams?
* Are you using the [example provided in the `amazon-ivs-react-native-player` codebase](https://github.com/aws/amazon-ivs-react-native-player/tree/main/example), or your own external application?
    * When using the internally provided example, are you able to manually switch to the 1080p quality in the `PlaygroundExample`?

On top of the above, it does appear that in the code snippets above you are attempting to set the qualities with `1920p60`, which does not correctly represent the 1080p option. For 1080p streams, if available, it should be `name: 1080p60`. But this can differ depending on the broadcast settings.

Instead you can [list all available qualities using the `onData` callback](https://github.com/aws/amazon-ivs-react-native-player/blob/main/example/src/screens/PlaygroundExample.tsx#L181), then [assign the 1080p quality to the `quality` prop](https://github.com/aws/amazon-ivs-react-native-player/blob/main/example/src/screens/PlaygroundExample.tsx#L133).

Please let me know if you have any additional questions. Thanks!

**Comment by RupamShaw** [comment]
this works
