### ISSUE TITLE
4XL API 30 android only hear voice video can't be seen black screen

### ISSUE THREAD

**Issue by RupamShaw** [aws/amazon-ivs-react-native-player#47]
Could hear voice of video in 4xl API 30 but can't view video its in simulator
```
<View style={{flex: 1}}>
          <IVSPlayer
            style={{flex: 1}}
<IVSPlayer
          streamUrl="https://fcc3ddae59ed.us-west-2.playback.live-video.net/api/video/v1/us-west-2.893648527354.channel.DmumNckWFTqz.m3u8"
     
          autoplay
        />
</View>
```
I can view above stream in samsung device

**Comment by alexmdodge** [comment]
Hi @RupamShaw! Thanks for submitting this report. Can you confirm a couple of details about the issue you've encountered?

* Can you confirm the configuration on your simulator?
* Can you provide any logs or network captures from your session?

In general it's known that Android Emulators [can often struggle with video playback](https://stackoverflow.com/a/13419712) depending on their configuration within Android Studio. With some more details about the Android emulator configuration I might be able to provide some additional insight.

Please let me know if you have any additional questions. Thanks!

**Comment by RupamShaw** [comment]
Thanks
Resolved
