### ISSUE TITLE
How to show controls in media player while video playing

### ISSUE THREAD

**Issue by manojmeena1988** [aws/amazon-ivs-react-native-player#49]
**Describe the bug**

**To reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Screenshots**

**Device (please complete the following information):**
 - Simulator or Real Device:
 - Device: [e.g. iPhone 12]
 - OS: [e.g. iOS 12.5]

**Debug logs**
You can turn on debug logging using the [logLevel prop](https://github.com/aws/amazon-ivs-react-native/blob/main/docs/ivs-player-reference.md#loglevel-optional).

**Additional context**

**Comment by manojmeena1988** [comment]
As there isn't any function or any props at least i am not able to see yet, can you/someone please tell us how to show/add controls in media player while playing video. As this is very important feature in any of the media player. Hopefully, this issue replied soon.

**Comment by maxstoller** [comment]
Hi manojmeena1988,

The SDK does not have built-in controls.

We do have an [example project](https://github.com/aws/amazon-ivs-react-native-player/blob/main/example/src/screens/AdvancedExample.tsx) that show how to implement controls. You should be able to mostly copy/paste that code as a starting point.

Also, we are working on [guidelines](https://github.com/aws/amazon-ivs-react-native-player/pull/26) that walk through how to build controls yourself.

Hope this helps!

**Comment by manojmeena1988** [comment]
Hy maxstoller,
Thanks for your earlier reply, It helped us a lot but finding some more issues with fullscreen ( landscape mode ). In some cases It takes complete screen but in some point of time it shows margin all around while video playing. Is there something in the package so we can manage it fluently.
Have you any reference for how to show landscape mode in fulll-screen while video playing.

**Comment by maxstoller** [comment]
Our next release will include a resizeMode prop, which I believe should solve your problem. Here is the PR in case you want to take an early look: https://github.com/aws/amazon-ivs-react-native-player/pull/42

**Comment by manojmeena1988** [comment]
Hello maxstoller,
Thanks again for your reply, but just want to know when we can expect the next release of this feature ?
Because it's became very needy feature for our mobile application.

**Comment by maxstoller** [comment]
We can’t provide specific target dates for features, but we are working on getting this out soon. You can subscribe to issue #12 to be notified when it’s released. Hope that helps.

**Comment by manojmeena1988** [comment]
Hello @maxstoller 
I am attaching a link of video [please see](https://share.webvision.dk/4guKAkjO) .
As you see, I switch from normal view to landscape mode and back again.
This results that the landscape mode shows video in 3 different sizes, and now we also have an issue that the normal view is also getting affected (the video looks like it's zoomed in). After switching the landscape mode several times, normal view shows video in not-zoomed-view again.

**Comment by maxstoller** [comment]
We released the resizeMode API. Can you please try that and see if it helps?

**Comment by manojmeena1988** [comment]
Hi @maxstoller 
You was right it is working fine as we are expecting. Just want to know one question here we are using seekSeconds feature (so we can specify from which point of time we want to start/play our video on first load) with your seekTo prop/ref in video player but it is working well in android but in ios it is not working. 
Have you some idea about it ?

**Comment by maxstoller** [comment]
Would you mind opening a new issue (bug report) for this? Please make sure to fill out as many details as possible. I will close this issue since the original questions have been addressed. Thanks!

**Comment by JKKholmatov** [comment]
> Hello [@maxstoller](https://github.com/maxstoller) I am attaching a link of video [please see](https://share.webvision.dk/4guKAkjO) . As you see, I switch from normal view to landscape mode and back again. This results that the landscape mode shows video in 3 different sizes, and now we also have an issue that the normal view is also getting affected (the video looks like it's zoomed in). After switching the landscape mode several times, normal view shows video in not-zoomed-view again.

@manojmeena1988 Hi! Could you please share how you managed to implement fullscreen mode and button? I am having trouble with hiding statusbar and navigation bars
