### ISSUE TITLE
IOS SILENT MODE sound in streaming not enabled by default

### ISSUE THREAD

**Issue by RupamShaw** [aws/amazon-ivs-react-native-player#50]
**Describe the bug**
IOS when side button silent mode off but streaming video doesn't have sound 
**To reproduce**
switch off side button and start streaming can't hear sound 

**Expected behavior**
I would like to override this feature even if side button turned off while streaming we can hear voice

**Screenshots**

**Device (please complete the following information):**
 - Simulator or Real Device:
 - Device: [e.g. iPhone 12]
 - OS: [e.g. iOS 12.5]
all devices 

"amazon-ivs-react-native-player": "1.0.0",
    "react": "17.0.1",
    "react-dom": "17.0.1",
    "react-native": "0.64.3",

**Comment by maxstoller** [comment]
Hi RupamnShaw, 

Can you please help me understand the question? When silent mode is enabled via the switch on the side of device, you want the player’s sound to still be audible? Is that correct?

Thanks!

**Comment by RupamShaw** [comment]
yes please, Because during start of streaming customers can't hear voice and requirement is on start of streaming they should hear voice.
Please let me know how I can do it in  this player. 
In react native video have this feature https://github.com/react-native-video/react-native-video/issues/2598 
via ignoreSilentSwitch.
Guidance can be helpful.
Please let me know.

**Comment by maxstoller** [comment]
Got it, thanks for clarifying. We don't have any immediate plans to support a `ignoreSilentSwitch` prop, but I will leave this feature request open for other to +1. In the meantime, we would welcome a PR if a developer wants to contribute this feature.

**Comment by RupamShaw** [comment]
HI Maxstoller... can you please guide how to implement this feature in IOS. Which file needs chage to add these so I can do it..My app is already in production so customer demand. Its needed your guidance of implementation. I could implement it.

https://github.com/aws/amazon-ivs-react-native-player/tree/main/ios#:~:text=5%20months%20ago-,AmazonIvsView.swift,-chore%3A%20set%20initialBufferDuration
what to change in this [AmazonIvsView.swift] then I will wireup everyting.
Thanks In advance maxstoller for helping

**Comment by alexmdodge** [comment]
Hi @RupamShaw! We actually implement this in the example application included within this repo:
https://github.com/aws/amazon-ivs-react-native-player/blob/main/example/ios/AmazonIvsExample/AppDelegate.m#L49

Note that this is generally an app level concern, so we may consider adding a helper for this in the future, but generally the above example should be sufficient and help cover cases where you may have multiple libraries which depend on this configuration.

You can read more about the `AVAudioSession` behavior on iOS here:
https://developer.apple.com/documentation/avfaudio/avaudiosession

**Comment by maxstoller** [comment]
Closing since the question has been answered, thanks!
