### ISSUE TITLE
Question: Is there way to set speed which the video should play?

### ISSUE THREAD

**Issue by pedrogarciyalopez** [aws/amazon-ivs-react-native-player#87]
Is there way to set speed which the video should play?

**Comment by maxstoller** [comment]
Hi @pedrogarciyalopez - yes, you can use the [playbackRate prop](https://github.com/aws/amazon-ivs-react-native-player/blob/main/docs/ivs-player-reference.md#playbackrate-optional).

**Comment by pedrogarciyalopez** [comment]
@maxstoller thank you
