### ISSUE TITLE
[Feature Request] Support for picture in picture for android and ios

### ISSUE THREAD

**Issue by vermadivyanshu** [aws/amazon-ivs-react-native-player#88]
We are using this package for video streaming in our mobile application, we would also like to support picture-in-picture mode for the same.
Like react native video: https://github.com/react-native-video/react-native-video/blob/master/API.md#pictureinpicture

is this something you plan on supporting in the near future?

**Comment by maxstoller** [comment]
Hi @vermadivyanshu, thanks for reaching out. We are looking into this and will get back to you here.

**Comment by vermadivyanshu** [comment]
@maxstoller thanks for responding. Do we have a concrete timeline on this? A month and year, which we are looking at for this to be released?

**Comment by maxstoller** [comment]
Hi @vermadivyanshu, I confirmed that we do support PiP in the native iOS and Android SDKs but not in the wrapper currently. I’ve shared this request with the team, but I am not able to provide a commitment or timeline. I will leave this open for others to :1. Thanks for the feedback.

**Comment by tomyates** [comment]
I would love to see this implemented too. Thanks guys!

**Comment by bhupendra128** [comment]
@maxstoller thanks for implementating this feature. Do we have any timeline to release this PIP feature ?

**Comment by pratikyadavr4** [comment]
I am also very excited about this feature and wanna know when will it get released?

**Comment by pugson** [comment]
How can I control this in an Expo app? I've added the required entitlements to `app.json` but using the `togglePip` ref function nothing happens.

```
"infoPlist": {
  "uiBackgroundModes": [
    "audio",
    "video",
    "picture-in-picture"
  ]
}
```

**Comment by bhupendra128** [comment]
@pugson is PIP working for you ?
We are also facing similar issue with attached examples as well for iOS.

**Comment by pugson** [comment]
No, it's not working. I can't get background playback to work with this library or `expo-av` at all on iOS 16.
