### ISSUE TITLE
ios: does not play audio with silent switch

### ISSUE THREAD

**Issue by hirbod** [aws/amazon-ivs-react-native-player#90]
**Describe the bug**
Currently, there is no way to play audio when the iPhone silent switch is active. Other libraries like expo-av or react-native-video have the ability to bypass this.

**To reproduce**
Try to play a video on iPhone with the silent switch set.

**Expected behavior**
I'd love to have the ability to bypass the silent switch restriction.

**Screenshots**

**Device (please complete the following information):**
 - Simulator or Real Device: Both
 - Device: all iPhone devicex
 - OS: tested with iOS 15 and 16

**Comment by hirbod** [comment]
I've seen that there has been an issue about this topic already and you guys pinpointed to https://github.com/aws/amazon-ivs-react-native-player/blob/main/example/ios/AmazonIvsExample/AppDelegate.m

Unfortunately, it does not work for me. Might be that I am also having an instance of expo-av, which maybe interferes, but even Expo-AVs 

```
Audio.setAudioModeAsync({
  playsInSilentModeIOS: true,
});
```

does not bypass this. Also tried different categories inside AppDelegate but I can't any sound when the mute switch is set. This might be an underlaying SDK thing.

**Comment by hirbod** [comment]
Indeed, the issue was happening due to expo-av. It always resets whatever you've set before. I deleted expo-av and provided functions for this directly in my package https://github.com/hirbod/react-native-volume-manager/

**Comment by maxstoller** [comment]
Hi @hirbod, glad you were able to figure it out. I’m going to close this since it sounds like an issue with expo-av.

**Comment by hirbod** [comment]
@maxstoller I'd still love to see this directly baked in as a simple method.
