### ISSUE TITLE
[bug][android]: no precise progress callback

### ISSUE THREAD

**Issue by hirbod** [aws/amazon-ivs-react-native-player#91]
**Describe the bug**
On iOS, the onProgress callback returns values like `76.14825396825397`, while Android just returns `76`. Building a slider on Android is not that smooth because of this, since I only have single seconds instead of precise float values.

**To reproduce**
Pass a callback to onProgress and log result

```ts

  const onProgress = (value) => {
        console.log(value)
  }
```

**Expected behavior**
Should return on both iOS and Android precise duration and progress values.

**Screenshots**

**Device (please complete the following information):**
 - Simulator or Real Device: Both
 - Device: Android
 - OS: Tested with Android 11, 12 and 13

**Comment by maxstoller** [comment]
Great feedback, thanks. We will look into this and see if we can make the Android behavior consistent with iOS for this API.
