### ISSUE TITLE
Android Build Fails: incompatible Kotlin version

### ISSUE THREAD

**Issue by vbylen** [aws/amazon-ivs-react-native-player#94]
Hi there,

I'm getting the following build error on android: 

```node
[stderr] e: /home/expo/workingdir/build/node_modules/amazon-ivs-react-native-player/android/src/main/java/com/amazonaws/ivs/reactnative/player/AmazonIvsViewManager.kt: (118, 10): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.1.15.
```

Should I just downgrade my Kotlin version to 1.1.15?

Thanks

**Comment by vbylen** [comment]
@hirbod `0.69.5`

**Comment by vbylen** [comment]
@hirbod, Thank you 🙏 

Yep I'm just using the expo-dev-client, but inside a monorepo. 

I'm wondering if that may be the issue.

**Comment by hirbod** [comment]
No, I also have a monorepo setup. I had the same problem with my very own library, which is super weird.
https://github.com/hirbod/react-native-volume-manager/issues/4

I fixed it for myself like so:
https://github.com/hirbod/react-native-volume-manager/commit/06a4a0141d42a1253c5657a2e19e6f231f2b1e3d#diff-197b190e4a3512994d2cebed8aff5479ff88e136b8cc7a4b148ec9c3945bd65aL1

I am wondering why IVS is not failing for me. I have another library, img.ly, which internally also changes the kotlin version, it might be the reason its working for me. You can for now just patch-package that line inside your node_modules until its resolved. RN 0.69+ required kotlin 1.6+

**Comment by hirbod** [comment]
@vbylen another solution which should work is to add following to your expo plugin section in your config.json/js

```json
{
  "expo": {
    "plugins": [
      [
        "expo-build-properties",
        {
          "android": {
            "kotlinVersion": "1.6.10"
          }
        }
      ]
    ]
  }
}
```

**Comment by vbylen** [comment]
@hirbod just what I was looking for, thank you!

**Comment by dawhitla** [comment]
Closing this issue a solution was given, and there has been no further questions 👍
