### ISSUE TITLE
[android] impossible to set autoplay to false

### ISSUE THREAD

**Issue by anatoleblanc** [aws/amazon-ivs-react-native-player#97]
**Describe the bug**
When setting autoplay={false} on android, video still starts.

**To reproduce**
Really simply: 
```
<TouchableOpacity onPress={()=>mediaPlayerRef.current?.pause()} style={{width:'100%', height:'100%', backgroundColor:"white", position:'absolute', zIndex:200}}>
    <View style={{height: 16/9*DEVICE_WIDTH, marginTop: dict_margin_top[mySize]}}>
      <IVSPlayer
        streamUrl={myUrl}                              
        style={[tw`w-full z-20 h-full`, {flex:1}]}
        ref={mediaPlayerRef}
        autoplay={false}
      > 
      </IVSPlayer>
    </View>
  </TouchableOpacity>
```

**Expected behavior**
the video should load but not play. 

**Device (please complete the following information):**
 - Device : Redmi Note 10S

**Comment by maxstoller** [comment]
Hi @anatoleblanc, thanks for the detailed report. We will look into this and get back to you.

**Comment by anatoleblanc** [comment]
Any news on this?

**Comment by maxstoller** [comment]
We don't have an update yet, but we will post here when we do. Thanks for your patience.

**Comment by anatoleblanc** [comment]
Thanks a lot for working on this! Would be a real life saver 🚀

**Comment by anatoleblanc** [comment]
Hi @maxstoller I found a solution let me know if it can be of any interest: 
I am just pausing the video on the native side when the player state is ready (if autoplay=true).
