### ISSUE TITLE
Player fails to load in Android

### ISSUE THREAD

**Issue by arthurgeron-work** [aws/amazon-ivs-react-native-player#99]
**Describe the bug**
Video does not play on android, the player stays in a loading loop, each load it crashes and then starts again.

**To reproduce**
Using version 1.2.0, try loading the following URL in a react-native application: `https://mobile.tradersclub.com.br/tcmediaapi/v1/file/hls/685d3dae-2f68-4f2f-be44-82a20f687716.m3u8`
I'm not using expo

**Expected behavior**
Should play the stream correctly or to call `onError` method

**Screenshots**

**Device (please complete the following information):**
 - Simulator or Real Device: Real Device
 - Device: Samsung a11
 - OS: One UI Core 3.1, Android 11
 
**Debug logs**

On App Launch the following is logged:
`Could not find generated setter for class com.amazonaws.ivs.reactnative.player.AmazonIvsViewManager`
`Could not find generated setter for class com.perrystreet.AwsIvsPlayerViewManager`
![image](https://user-images.githubusercontent.com/71399856/195651613-d5a4400d-84dc-4696-9507-670a263a2744.png)

When video tries to play it logs:
![Captura de Tela 2022-10-13 às 13 25 22](https://user-images.githubusercontent.com/71399856/195652515-06d17b36-4234-4264-b1dd-1851f6a5c08a.png)

**Additional context**

**Comment by arthurgeron-work** [comment]
Identified that this only happens if all available qualities resolutions can't be decoded by the Android device

**Comment by maxstoller** [comment]
Hi @arthurgeron-work, I noticed this content is not an IVS stream. The IVS player SDK is designed to work with IVS content. Playback of 3P content is considered best-effort. 

Based on the decode error in the logs, it looks like the device is not able to decode the 1280x2274 stream. I think the Snapdragon 450 chipset used in the Samsung A11 only supports up to 1080p. I suggest trying a 1080x1920 stream. 

I will bring this feedback to the team and see if we can better handle these errors.

**Comment by arthurgeron-work** [comment]
I see! Only that I think the player shouldn't be switching to a null quality and trying to load it anyway, instead at least it should trigger the react "onError" method right?

**Comment by maxstoller** [comment]
@arthurgeron-work Just to confirm, does the app crash when you try to play the stream, or does playback fail without onError being triggered?

**Comment by arthurgeron-work** [comment]
The player throws an exception in the Native level but it does not bubble up to the JS Thread, the player keeps looping.

**Comment by arthurgeron-work** [comment]
I'm recording a video right now to clarify

**Comment by arthurgeron-work** [comment]
@maxstoller 
https://user-images.githubusercontent.com/71399856/195664847-e9278dc9-3666-4ee6-be41-27aa0d9ee859.mp4

**Comment by maxstoller** [comment]
It looks like the app doesn't crash, but onError is never triggered even though the video is not decodable. The issue is clear now. Thanks for the video.
